=== rcorcas036/GradoSuperior/XML/xsdexamen.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Majid Nasab (Galileo International) -->
<xs:schema  xmlns="http://ns.galileo.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GWS_FlightInformationRQ">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Flights" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Flight" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="airline" type="xs:string"/>
									<xs:attribute name="number" type="xs:string"/>
									<xs:attribute name="date" type="xs:string"/>
									<xs:attribute name="orig" type="xs:string" use="optional"/>
									<xs:attribute name="dest" type="xs:string" use="optional"/>
									<xs:attribute name="bic" type="xs:string" use="optional"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="returnFlightServiceInfo" type="xs:boolean" use="optional" default="0"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== rcorcas036/GradoSuperior/XML/Ejercicio 3 examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<GWS_FlightInformationRQ xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="xsdexamen.xsd">
<Flights>
    <Flight returnFlightServiceInfo=0>
        <airline>Alsa</airline>
        <number>892</number>
        <date>02/09/2020</date>
        <orig>Kansas</orig>
        <dest>Huelva</dest>
        <bic>Mercancia</bic>
        </Flight>
    <Flight returnFlightServiceInfo=1>
        <airline>Asahi</airline>
        <number>712</number>
        <date>12/09/2020</date>
        <orig>Cordoba</orig>
        <dest>Caracas</dest>
        <bic>Transporte</bic>
    </Flight>
</Flights>
</GWS_FlightInformationRQ>
