=== rcorcas036/GradoSuperior/XML/payments/payments2.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="payments">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="dni" >
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:pattern value="[0-9]{8}[A-Z]"></xs:pattern>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>  
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="birthDate">
                        <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="xs:date">
                                        <xs:attribute name="age">                                        
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                        <xs:minInclusive value="0"/>
                                                        <xs:maxInclusive value="120"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:attribute>
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                </xs:element>
                <xs:element name="time" type="xs:time" maxOccurs="unbounded" />
                <xs:element name="price" type="xs:decimal" />
                <xs:element name="amount" type="xs:positiveInteger" />
                <xs:element name="paid" type="xs:boolean" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== rcorcas036/GradoSuperior/XML/payments/payments.xml
<?xml version="1.0" encoding="UTF-8" ?>
<payments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="payments2.xsd">
    <name dni="12345678A">Javier Toledano</name>
    <birthDate age="23">1998-02-04</birthDate>
    <time>23:55:15</time>
    <time>23:55:15</time>
    <price>123.56</price>
    <amount>678</amount>
    <paid>true</paid>
</payments>
